name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - release
    tags:
      - 'v*'

jobs:
  publish-talkyai:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libgtk-3-dev

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: npm install

      - name: Prepare release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const cfgPath = path.join('src-tauri', 'tauri.conf.json');
            const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
            const version = cfg.version || '';
            const notesPath = path.join('notes', `v${version}.change_notes.md`);
            let body = 'See the assets to download this version and install.';
            if (fs.existsSync(notesPath)) {
              body = fs.readFileSync(notesPath, 'utf8');
            } else {
              core.warning(`Change notes file not found: ${notesPath}. Using default body.`);
            }
            core.setOutput('body', body);

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'TalkyAI Studio v__VERSION__'
          releaseBody: ${{ steps.notes.outputs.body }}
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: talkyai-studio-${{ matrix.platform }}-${{ matrix.args }}
          path: |
            src-tauri/target/release/bundle/**/*
            src-tauri/target/release/*
